// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svpvcihdlekrcnvvldmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2cHZjaWhkbGVrcmNudnZsZG1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxODk4NDUsImV4cCI6MjA3NTc2NTg0NX0.bJJxbOO8PF6MoVH1BFceiK6V66VRHWc7_1t-p4PBd2E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});